name: bimatarung_design_system
description: A new Flutter package project.
version: 2.3.3
homepage: "https://github.com/banua-coder/bimatarung-design-system"

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dotted_border: ^2.0.0+3
  extended_image: ^8.0.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.2
  flutter_spinkit: ^5.2.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  nil: ^1.1.1
  pinput: ^2.2.31
  reactive_forms: ^14.3.0
  shimmer: ^3.0.0
  tap_debouncer: ^2.2.0
  timelines: ^0.1.0

dev_dependencies:
  dart_code_metrics: ^5.7.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
flutter_gen:
  output: lib/src/core/assets/gen/
